---
title: "Abstract"
author: "Puwasala Gamakumara"
date: "ACEMS Retreat 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Low-cost in-situ sensors are used to monitor and manage water quality in river networks, by taking regular measurements from different water-quality variables at high frequencies. The data generated by these sensors are prone to errors due to mis-calibration, bio-fouling, weakening battery charge or any other technical failures. We propose a novel statistical framework based on Generalised Additive Models (GAM), to detect anomalies in these water-quality variables. The proposed method involves building a GAM for the water-quality variable measured downstream, using related lagged predictors from the upstream sensor. The lag time between sensors is estimated using cross-correlation methods. Residuals from the fitted model are then used to detect anomalies following the Peak Over Threshold method based on Extreme Value Theory. We also show that utilising the information from the upstream sensor reduces the false negative rate compared to using only predictors from the same sensor location. 


